GET http://localhost:3000/ HTTP/1.1

###


GET http://localhost:3000/product/ HTTP/1.1

###
GET http://localhost:3000/Data HTTP/1.1


###
GET http://localhost:3000/Data/FullOfSun HTTP/1.1

###
GET http://localhost:3000/Data/FullOfSun/description HTTP/1.1